<?php
/**
 * @package cc_reviews
 */
/**
Plugin Name: Doctor Reviews
Plugin URI: https://cleancoded.com/plugins
Description: Custom Doctor Reviews plugin, extendable, reusable under GPL v3 License | Made by cleancoded.com
Version:1.0
Author: cleancoded.com
Author URI: https://cleancoded.com
License: GPL V2 or later
Text Domain: cc_reviews
*/
defined('ABSPATH') or die("Are you sure you want to do this?");
if ( ! function_exists('doctor_reviews_post_type') ) {

// Register Custom Post Type
function doctor_reviews_post_type() {

	$labels = array(
		'name'                  => _x( 'Doctor Reviews', 'Post Type General Name', 'cc_reviews' ),
		'singular_name'         => _x( 'Doctor Review', 'Post Type Singular Name', 'cc_reviews' ),
		'menu_name'             => __( 'Doctor Reviews', 'cc_reviews' ),
		'name_admin_bar'        => __( 'Doctor Review', 'cc_reviews' ),
		'archives'              => __( 'Item Archives', 'cc_reviews' ),
		'attributes'            => __( 'Item Attributes', 'cc_reviews' ),
		'parent_item_colon'     => __( 'Parent Item:', 'cc_reviews' ),
		'all_items'             => __( 'All Reviews', 'cc_reviews' ),
		'add_new_item'          => __( 'Add New Review', 'cc_reviews' ),
		'add_new'               => __( 'Add New', 'cc_reviews' ),
		'new_item'              => __( 'New Review', 'cc_reviews' ),
		'edit_item'             => __( 'Edit Review', 'cc_reviews' ),
		'update_item'           => __( 'Update Review', 'cc_reviews' ),
		'view_item'             => __( 'View Review', 'cc_reviews' ),
		'view_items'            => __( 'View Reviews', 'cc_reviews' ),
		'search_items'          => __( 'Search Review', 'cc_reviews' ),
		'not_found'             => __( 'Not found', 'cc_reviews' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'cc_reviews' ),
		'featured_image'        => __( 'Featured Image', 'cc_reviews' ),
		'set_featured_image'    => __( 'Set featured image', 'cc_reviews' ),
		'remove_featured_image' => __( 'Remove featured image', 'cc_reviews' ),
		'use_featured_image'    => __( 'Use as featured image', 'cc_reviews' ),
		'insert_into_item'      => __( 'Insert into item', 'cc_reviews' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'cc_reviews' ),
		'items_list'            => __( 'Items list', 'cc_reviews' ),
		'items_list_navigation' => __( 'Items list navigation', 'cc_reviews' ),
		'filter_items_list'     => __( 'Filter items list', 'cc_reviews' ),
	);
	$args = array(
		'label'                 => __( 'Doctor Review', 'cc_reviews' ),
		'description'           => __( 'Add reviews feature to doctor post type', 'cc_reviews' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'revisions', 'custom-fields', 'page-attributes', ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-admin-comments',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'doctor_reviews', $args );

}
add_action( 'init', 'doctor_reviews_post_type', 0 );

}

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function review_details_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function review_details_add_meta_box() {
	add_meta_box(
		'review_details-review-details',
		__( 'Review Details', 'review_details' ),
		'review_details_html',
		'doctor_reviews',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'review_details_add_meta_box' );

function review_details_html( $post) {
	wp_nonce_field( '_review_details_nonce', 'review_details_nonce' ); ?>

	<p>
		<label for="review_details_choose_doctor"><?php _e( 'Choose Doctor', 'review_details' ); ?></label><br>
<?php 
 //get doctor array
$doctors = get_posts(array('posts_per_page' => -1, 'post_type'=>'doctors'));
 ?>

<?php
  $chosen_doc = ( maybe_unserialize(get_post_meta( $post->ID, 'review_details_choose_doctor', false )));
  foreach($chosen_doc as $ch_doc){
  print_r ($ch_doc);
  }
  ?>
		<select name="review_details_choose_doctor[]" multiple="multiple" id="review_details_choose_doctor">
<?php
  $get_selected_doc = explode(",", review_details_get_meta( 'review_details_choose_doctor' ));
foreach($doctors as $doctor)
{ 
  
echo  '<option value="'.$doctor->ID.'"'. (in_array($doctor->ID,$get_selected_doc) ? 'selected' : '').'>'.$doctor->post_title.'</option>';
}
?>
		</select>

	</p>	<p>
		<label for="review_details_rating"><?php _e( 'Rating', 'review_details' ); ?></label><br>
<?php  $rating = array(1,2,3,4,5);
?>
		<select name="review_details_rating" id="review_details_rating">
<?php
	foreach($rating	as $rating_value){
echo	'<option value="'.$rating_value.'"'. ((review_details_get_meta( 'review_details_rating' ) == $rating_value ) ? 'selected' : '').'>'.$rating_value.'</option>';
}
?>
		</select>
	</p>	<p>
		<label for="review_details_speciality"><?php _e( 'Speciality', 'review_details' ); ?></label><br>
<?php  $taxonomies = get_terms(array('taxonomy'=>'doctors_treatments', 'hide_empty'=> false));
?>
		<select name="review_details_speciality" id="review_details_speciality">
<?php
	foreach($taxonomies	as $taxonomies_value){
echo	'<option value="'.$taxonomies_value->term_id.'"'. ((review_details_get_meta( 'review_details_speciality' ) == $taxonomies_value->term_id ) ? 'selected' : '').'>'.$taxonomies_value->name.'</option>';
}
?>
		</select>
	</p><?php
//get users
$wp_users_list = get_users();
?>
<label>Choose User</label><br/>
<select name="review_details_user" id="review_details_user">

<?php 
  foreach($wp_users_list as $user_obj){
echo '<option value="'.$user_obj->ID.'" '. ((review_details_get_meta( 'review_details_user' ) == $user_obj->ID ) ? 'selected' : '').'>'.$user_obj->display_name.'</option>';
}
?>
</select>
<p><label>Source</label>
<br/>
  
		<input type="text" name="review_details_source" id="review_details_source" value="<?php echo review_details_get_meta( 'review_details_source'); ?>">
</p>
<?php
}

function review_details_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['review_details_nonce'] ) || ! wp_verify_nonce( $_POST['review_details_nonce'], '_review_details_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['review_details_choose_doctor'] ) )
		update_post_meta( $post_id, 'review_details_choose_doctor', esc_attr( implode(",",$_POST['review_details_choose_doctor'] ) ) );
  	if ( isset( $_POST['review_details_speciality'] ) )
		update_post_meta( $post_id, 'review_details_speciality', esc_attr( $_POST['review_details_speciality'] ) );
	if ( isset( $_POST['review_details_rating'] ) )
		update_post_meta( $post_id, 'review_details_rating', esc_attr( $_POST['review_details_rating'] ) );
		if ( isset( $_POST['review_details_user'] ) )
		update_post_meta( $post_id, 'review_details_user', esc_attr( $_POST['review_details_user'] ) );
  if ( isset( $_POST['review_details_source'] ) )
		update_post_meta( $post_id, 'review_details_source', esc_attr( $_POST['review_details_source'] ) );
}
add_action( 'save_post', 'review_details_save' );

/*
	Usage: review_details_get_meta( 'review_details_choose_doctor' )
	Usage: review_details_get_meta( 'review_details_rating' )
*/



//shortcode for review - single item

if(!function_exists('get_review_single')){
  function get_review_single($atts, $content=null){
      //atts not being used
       $get_doc_id = $_GET['doctor_id'];
    if( empty($_GET['doctor_id']) || $get_doc_id===''){
      return sprintf(__('<h2>%s</h2>'), 'Invalid Request');
    }
      
        //get reviews
        
        $reviews_doc = get_posts(array(
        	'post_type'=> 'doctor_reviews', 
        	'meta_query'=> array(
          array(
          'key'=> 'review_details_choose_doctor', 
        	'value'=>$get_doc_id,
          'compare'=>'LIKE'
          )),
        	 'posts_per_page' => -1
        	));
        $testimonials_doc = get_posts(array(
        	'post_type' => 'doctor_testimonials',
        	'meta_query'=>array(array(
          'key' => 'testimonial_details_choose_doctor',
        	'value' => $get_doc_id,
          'compare'=>'LIKE'
          )),
        	'posts_per_page' => -1
        ));
    //define tab active variable
     $tab_active = NULL;
       //get doctor id
   // var_dump($reviews_doc); ?>
<div class="container testimonials-solo-page ">
     <section class="top-content page-content">
			  <h1>Patient Testimonials and Reviews</h1>
				<div class="search-form row">
					<?php
					$_tab_open = $_GET['tab_open'] != '' ? $_GET['tab_open'] : '';
					$_doctor_id = $_GET['doctor_id'] != '' ? $_GET['doctor_id'] : '';
					$doctor_name ='';
					$doctor_email='';
					if($_doctor_id){
						$doctor_name=get_post_meta( $_doctor_id , 'doctor_name', true );
						$doctors_last_name=get_post_meta( $_doctor_id , 'doctors_last_name', true );
						$terms=get_post_meta( $_doctor_id , 'speciality_taxonomy', true );
						$doctor_phone=get_post_meta( $_doctor_id , 'phone', true );
						$degrees =[];
						if( get_field('degrees', $_doctor_id) )
						{
							while( the_repeater_field('degrees', $_doctor_id) )
							{
								$degrees[] =  get_sub_field('degree');
							}
						}
					}
					?>
					<figure class="col-sm-3 doc-img col-xs-12">
						<?php 
						$image = get_field('photo', $_doctor_id);
						if($image){
							$size = 'thumbnail';
							$thumb = $image['sizes'][ $size ];
							$width = $image['sizes'][ $size . '-width' ];
							$height = $image['sizes'][ $size . '-height' ]; ?>
							<img  src="<?php echo $thumb; ?>" alt="<?php echo $alt; ?>" width="255" height="255" class="thumbnail"/>
						 <?php }else{?>
								<img  src="<?php  echo esc_url( home_url('/'));?>wp-content/uploads/2017/05/nopic.png" class="thumbnail"/>
						 <?php }?>
					</figure>
					<div class="col-sm-9 doc-info col-xs-12">
              <h2>
                <?php echo $doctor_name.' '.$doctors_last_name.' '.implode(" ",$degrees); ?>
              </h2>
              <p>
                <?php
							if(!empty($terms)):
								foreach( $terms as  $id ):
								   $term = get_term( $id, 'doctors_treatments');
								   if($term->parent == 0){ echo $term->name.",";}
								endforeach;
							endif;
						 ?>
              </p>
              <p class="tel">
                Phone: <?php echo $doctor_phone; ?>
              </p>
              <div class="cta-btns">
                  <a class="btn-filled-big" target="_self"
                   href="
                    <?php  echo get_permalink($_doctor_id); ?>">view profile<i class="fa fa-angle-right"></i>
                  </a>
              </div>
            </div>
				</div>
         </section>
  <?php if(empty($reviews_doc) && empty($testimonials_doc)){ return _e("<h2>No Reviews found for this doctor.</h2>");} ?>
  <section class="tabs-block horizontal-tabs clearfix">
				    <ul class="tabs">
           	<?php
    				if(!empty($testimonials_doc) && count($testimonials_doc) > 0):
				?>         <li onclick="testimonialsTab(event, 'physician_testimonials')" class='<?php if($_GET['tab_open'] == "testimonial"){echo "tablinks tab current"; } else { echo "tablinks tab";}?>' data-tab="tab1"><span>
        	<?php   if($_GET['tab_open'] == "testimonial"){$tab_active = 'defaultOpen';} ?>
					    <a id="<?php echo $tab_active; ?>"><?php _e('TESTIMONIALS'); ?></a>
					  <?php endif; ?>
                </span></li>
            <?php if(!empty($reviews_doc) ):?>
					    <li onclick="testimonialsTab(event, 'physician_reviews')"  class='<?php if($_GET['tab_open'] == "review"){echo "tablinks tab current"; } else { echo "tablinks tab";}?>' data-tab="tab2"><span>
					  <?php if($_GET['tab_open'] == "review"){$tab_active = 'defaultOpen';} ?>
					    <a id="<?php echo $tab_active; ?>"><?php _e('PATIENT REVIEWS'); ?></a>
					  <?php endif;?>
                </span></li>
					</ul>
  <div class="tab-content-wrapper horizontal-tabs-content">
         <div class="tab-content-block current" id="tab1">
                            <div class="tabs-block2 vertical-tabs">
                                <div class="row">
					<?php if( !empty($testimonials_doc) ):?>
						<div id="physician_testimonials" class="tabcontent">
							<div class="left_tab col-sm-3 col-xs-12">
                <ul class="tabs">
							<?php
							   foreach( $testimonials_doc as $testimonial_doc) {
								 ?>
								 <li class="tab"><a class="left_tablinks"
								 onclick="testimonialsLeftTab(event, '<?php echo $testimonial_doc->post_title; ?>')" id="defaultOpenleft"><?php echo $testimonial_doc->post_title; ?></a>
                   </li>
							<?php }?>
                  </ul>
							</div>
              <div class="col-sm-9 vertical-tab-content-wrapper col-xs-12">
							  <?php
							   foreach( $testimonials_doc as $testimonial_doc )
								{
								printf(__('<div id="%s" class="left_tabcontent testimonial-content vertical-tab-content current">'),$testimonial_doc->post_title);
									printf(__('<a href="%s"><img src="%s"></a>'), get_the_permalink($testimonial_doc->ID), get_the_post_thumbnail_url($testimonial_doc->ID));
									echo   $testimonial_doc->post_content;
								
							   ?>	
                
                      <?php 
          $related_user_id = get_userdata(get_post_meta($testimonial_doc->ID, 'testimonial_details_user', 'true'))->ID;
                  echo '<h2>'.get_userdata($related_user_id)->display_name.' Doctors:</h2>';
      //echo "ID:" .$related_user_id;
      $get_doctors_list = explode(",",(get_post_meta($testimonial_doc->ID, 'testimonial_details_choose_doctor', 'true')));
                  // print_r($get_doctors_related_list);
      ?>
      <div style="clear:both;margin:10px;"></div>
      <?php
      foreach($get_doctors_list as $related_doctor){
      ?>
      <?php $doc_info = get_post($related_doctor); ?>
      <?php
      if($_GET['doctor_id'] != $doc_info->ID){
      	echo '<div class="related_doctor col-md-6">';
          $img = get_field('photo', $doc_info->ID); ?>
      
        <div class="col-md-4"><figure class="doc-photo"><a href="#!" class="thumbnail"><img src="<?php echo $img['sizes']['thumbnail'] ?>" /></a></figure>
          </div>
          <div class="col-md-8 doc-info"><?php
            		printf(__('<h3 class="doc_name"><a href="%s">%s</a></h3>'), get_the_permalink($doc_info->ID), $doc_info->post_title);
			 ?>
			 <p class="specilty" style="line-height:1.5;font-size:12px;">Specialty: <span><?php 
      //get terms 
      $get_terms = get_field('speciality_taxonomy', $doc_info->ID);
       foreach($get_terms as $term_id){
         $category = get_term($term_id);
         echo $category->name. ",";
       }
         ?>
         </span>
      </p>
             <p class="location">Location: <span>   <?php
        if (have_rows('add_locations', $doc_info->ID)):
               while (have_rows('add_locations', $doc_info->ID)):
                the_row();
                $locations = get_sub_field('select_location', $doc_info->ID);
                if ($locations):
                    for ($i = 0; $i < count($locations); $i++):
                        echo get_field('location_city', $locations[$i]->ID) . ' ' . get_field('location_zip', $locations[$i]->ID) . ' ';
                    endfor;
                endif;
            endwhile;
        else:
            echo "N/A";
        endif;
               ?></span></p>
           
            <div class="cta-btns">
                        <?php		
                        printf(__('<a class="btn-filled-big" href="%s">%s <i class="fa fa-angle-right"></i></a>'), get_the_permalink($doc_info->ID), 'VIEW PROFILE'); ?>

            </div>
          </div>
          </div>
      <?php
  }
      }
      ?>
  </div>
      <?php
		}	  endif; ?>
          	</div>
           </div>
        </div>
    <?php if( !empty($reviews_doc) ): ?>
						<div id="physician_reviews" class="tabcontent">
               
    
    <div class="review_list">
      <?php
		foreach($reviews_doc as $review_doc){
      
      ?> <div class="review" style="margin-bottom:20px; background-color:#EEE;padding:20px;">
          <div class="review-heading">
      <div class="col-md-12">
         <div class="pull-left"> <h4><a href="<?php echo get_post_permalink($review_doc->ID); ?>"><?php echo $review_doc->post_title; ?></a></h4>
         </div><div class="pull-right">
        <?php $rating = get_post_meta($review_doc->ID, 'review_details_rating', 'true');
         	for($rating_count= 0 ; $rating_count < $rating; $rating_count++){
            echo '<i class="fa fa-star" style="color:yellow;"></i>'; 
          }
        ?>
         </div>
            </div>
         <p><i>On:</i> <?php echo get_the_date($format='', $review_doc->ID); ?> By: 	<?php echo  get_userdata(get_post_meta($review_doc->ID, 'review_details_user', 'true'))->display_name; ?></p>
    </div>
         <hr>
    <div class="review_content">
        <?php echo $review_doc->post_content; ?>
    </div>
     
     <div class="review_info">
     	<p><strong>Source: </strong><?php
     	 echo get_post_meta($review_doc->ID, 'review_details_source', 'true'); ?></p>
     </div>
      </div>
     	<?php
      ?>
      
      	<?php 
          $related_user_id = get_userdata(get_post_meta($review_doc->ID, 'review_details_user', 'true'))->ID;
      echo '<h2>'.get_userdata($related_user_id)->display_name.' Docotors</h2>';
      $get_doctors_list = explode(",", (get_post_meta($review_doc->ID, 'review_details_choose_doctor', true)));
     // print_r($get_doctors_related_list);
      ?>
      <div style="clear:both;margin:10px;"></div>
      <?php
      foreach($get_doctors_list as $related_doctor){
      ?>
      <?php $doc_info = get_post($related_doctor); ?>
      <?php
          if($_GET['doctor_id'] != $doc_info->ID){
        echo '<div class="related_doctor col-md-6">';
            $img = get_field('photo', $doc_info->ID); ?>
        <div class="col-md-4"><figure class="doc-photo"><a href="#!" class="thumbnail"><img src="<?php echo $img['sizes']['thumbnail'] ?>" /></a></figure>
          </div>
          <div class="col-md-8 doc-info"><?php
            		printf(__('<h3 class="doc_name"><a href="%s">%s</a></h3>'), get_the_permalink($doc_info->ID), $doc_info->post_title);
			 ?>
			 <p class="specilty" style="line-height:1.5;font-size:12px;">Specialty: <span><?php 
      //get terms 
      $get_terms = get_field('speciality_taxonomy', $doc_info->ID);
       foreach($get_terms as $term_id){
         $category = get_term($term_id);
         echo $category->name. ",";
       }
         ?>
         </span>
      </p>
             <p class="location">Location: <span>   <?php
        if (have_rows('add_locations', $doc_info->ID)):
               while (have_rows('add_locations', $doc_info->ID)):
                the_row();
                $locations = get_sub_field('select_location', $doc_info->ID);
                if ($locations):
                    for ($i = 0; $i < count($locations); $i++):
                        echo get_field('location_city', $locations[$i]->ID) . ' ' . get_field('location_zip', $locations[$i]->ID) . ' ';
                    endfor;
                endif;
            endwhile;
        else:
            echo "N/A";
        endif;
               ?></span></p>
           
            <div class="cta-btns">
                        <?php		
                        printf(__('<a class="btn-filled-big" href="%s">%s <i class="fa fa-angle-right"></i></a>'), get_the_permalink($doc_info->ID), 'VIEW PROFILE'); ?>

            </div>
          </div>
          </div>
      <?php
      }
      }
    } ?> </div></div><?php  endif; ?>
</div>
</section>
</div>


<?php  }
}
add_shortcode('get_review', 'get_review_single');

//filter shortcode, mostly same code used as in doctorssearch filter

//	Testimonials and Reviews
		function review_filter(){
				$a='<form class="horizontal-form search-patient-reviews" method="GET"  action="'.$_SERVER['REQUEST_URI'].'">
					<h5>SEARCH PATIENT REVIEWS</h5>';
				$a.='
				<div class="input-group field-1 large">
					<input class="form-control" type="text" autocomplete="off"  name="physcian_name" id= "physcian_name"
					placeholder="Physician Name" value="'.$_POST['physcian_name'].'">
				</div>
				';
				//$testimonials_reviews = get_field_object("field_59e72b66fa497");
				$a.='
				<div class="input-group select-box field-2 large">
					<i class="fa fa-angle-down"></i>
					<select name="testimonials_reviews" class="form-control" id="testimonials_reviews">';
						$a.='<option value=" ">All</option>';
						$a.='<option value="Testimonial"';
						if($_POST['testimonials_reviews'] == "Testimonial" ){$a.='selected';}
						$a.='>Testimonial</option>';
						$a.='<option value="Review"';
						if($_POST['testimonials_reviews'] == "Review" ){$a.='selected';}
						$a.='>Review</option>';
				$a.='</select></div>';
				$terms = get_terms( array(
					'taxonomy' => 'doctors_treatments',
					'hide_empty' => false,'orderby' => 'name',
					'order' => 'ASC','parent' => 0
				) );
				$a.='
				<div class="input-group select-box field-3 medium">
                    <i class="fa fa-angle-down"></i>
					<select name="specialityTags" id="specialityTags" class="form-control">';
					$a.='<option value=" ">Speciality</option>';
					foreach( $terms as  $value )
				        {
				            $a.='<option value="' . $value->term_id . '"';
										if($_POST['specialityTags'] == $value->term_id ){$a.='selected';}
										 $a.='>'.$value->name . '</option>';
				        }
					$a.='</select>
				</div>
				';
				
				$a.='
				<div class="input-group submit">
					<i class="fa fa-search"></i>
					<input type="submit" id="searchsubmit" name="searchsubmit" class="submit-btn" value="GO"></input>
				</div>
				</form>';
				return $a;
		}
		add_shortcode('review-filter','review_filter');

//enqueue scripts

function enqueue_review_plugin_scripts(){
  //add script
  wp_enqueue_script("tabs_script", plugin_dir_url(__FILE__).'/script.js', array('jquery'), 1.0, true);
}

add_action('wp_enqueue_scripts', 'enqueue_review_plugin_scripts');
